---

- name: deploy LEMP stack
  hosts: lemp1
  sudo: yes

  roles:
    - common
    - dbservers
    - webservers
    - php5


- name: deploy websites to one host
  hosts: lemp1
  sudo: yes
  vars_files:
    #use different sites-hostname.yml to deploy websites to different hosts
    - roles/websites/files/sites-{{ inventory_hostname }}.yml

  roles:
    - websites

