---
- name: install mysql server and python-mysqldb
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server 
    - python-mysqldb 
  notify:
    - start mysql

- name: backup my.cnf to my.cnf.orig
  command: creates=/etc/mysql/my.cnf.orig
           cp /etc/mysql/my.cnf /etc/mysql/my.cnf.orig

- name: create mysql user
  mysql_user: name={{ db_user }}  host=% password={{ db_pass }} priv=*.*:ALL state=present 

- name: create mysql db
  mysql_db: name={{ db_name }} state=present

